-- ROLES
INSERT INTO role (name) VALUES ('EMPLOYEE');
INSERT INTO role (name) VALUES ('ADMINISTRATOR');
INSERT INTO role (name) VALUES ('ASSISTANT_OWNER')
INSERT INTO role (name) VALUES ('OWNER');

-- PERMISSIONS
