CREATE TABLE IF NOT EXISTS module (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    base_path VARCHAR(255) UNIQUE NOT NULL
);

CREATE IF NOT EXISTS operation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    PATH VARCHAR(255) NOT NULL,
    http_method VARCHAR(10) NOT NULL,
    permit_all BOOLEAN NOT NULL,
    module_id BIGINT UNSIGNED,
    CONSTRAINT fk_module
        FOREIGN KEY (module_id)
        REFERENCES module(id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS granted_permission (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    role_id BIGINT UNSIGNED NOT NULL,
    operation_id BIGINT UNSIGNED NOT NULL,
    CONSTRAINT fk_role
        FOREIGN KEY (role_id)
        REFERENCES role(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_operation
        FOREIGN KEY (operation_id)
        REFERENCES operation(id)
        ON DELETE SET NULL
    )
);